### ISSUE TITLE
Transforming some outputs into latches

### ISSUE THREAD

**Issue by gaperez64** [arminbiere/aiger#1]
Hi Armin,

Do you see an easy way of using/chaining the current binaries to transform some of the outputs of an aiger file into latches? It's an easy program, but just wanted to check with you before reinventing the wheel.

Cheers,
Guillermo

**Comment by arminbiere** [comment]
What do you mean by 'binaries'?  Is it 'literals'?  In any case turning some of the  outputs into latches should be straight-forward (do you still want to pass them through as latches)?  You could do this with scripts on the ASCII format or by hacking a small tool.  There are plenty of examples where some non-latch literals are added or removed or copied to a new aiger model.  Maybe 'aigreset.c' is the closest one in functionality ....

**Comment by gaperez64** [comment]
> What do you mean by 'binaries'? Is it 'literals'? In any case turning some of the outputs into latches should be straight-forward (do you still want to pass them through as latches)? You could do this with scripts on the ASCII format or by hacking a small tool. There are plenty of examples where some non-latch literals are added or removed or copied to a new aiger model. Maybe 'aigreset.c' is the closest one in functionality ....

By 'binaries' I meant the existing tools. I will take a look at `aigreset.c` and hack something small then. Many thanks for the quick feedback!
