### ISSUE TITLE
smvtoaig not working

### ISSUE THREAD

**Issue by DonCyriac** [arminbiere/aiger#2]
I am not able to convert *.smv files.

**Comment by arminbiere** [comment]
Please be more specific and explain your problem in detail.

**Comment by DonCyriac** [comment]
I tried with the original .smv file and it was generating errors. But  then I saw in this document [http://fmv.jku.at/papers/Biere-FMV-TR-07-1.pdf](url) that you are giving the flattened and binary encoded smv model as the input to smvtoaig. 
The issue was raised because it was not mentioned explicitly. Do you have any directions for how to use smvtoaig?

**Comment by DonCyriac** [comment]
Found **smvflatten**.
Closing the issue.
